### ISSUE TITLE
大佬，能否支持一下空闲线程自动释放？

### ISSUE THREAD

**Issue by ChunelFeng** [lzpong/threadpool#10]
rt

**Comment by lzpong** [comment]
已支持 [commit 2e0c5e8](https://github.com/lzpong/threadpool/commit/2e0c5e8586947c4f7d354a81c058f9896f1a7f71)

**Comment by ChunelFeng** [comment]
很开心看到您的回复。 我前段时间，也实现了一个可以自动缩扩容的C++的线程池，跟大佬分享。
也请大佬帮忙review一下：
https://github.com/ChunelFeng/CGraph/blob/main/tutorial/TU01-ThreadPool.cpp

**Comment by lzpong** [comment]
我觉得, 初始1~2个线程,开启自动增长, 空闲自动释放应该也不错吧, 省一个监控线程
