### ISSUE TITLE
在只剩下一个空闲线程时，多个任务同时commit, 会发生什么？

### ISSUE THREAD

**Issue by liuyong2000** [lzpong/threadpool#16]
这是一个race condition的情况，
```
#ifdef THREADPOOL_AUTO_GROW
		if (_idlThrNum < 1 && _pool.size() < THREADPOOL_MAX_NUM)
			addThread(1);
#endif // !THREADPOOL_AUTO_GROW
		_task_cv.notify_one(); // 唤醒一个线程执行
```
如果还有一个线程，多个commit同时发生，if 为 false, 直接执行notify, 而不会创建新的线程，有且仅有一个线程被唤醒，而且任务执行完也不判断任务队列的空与否，那么有的任务永远不会被执行。

另外，addThread里没有锁保护，下面的判断也会出错
```
void addThread(unsigned short size)
	{
		for (; _pool.size() < THREADPOOL_MAX_NUM && size > 0; --size)
```
同时调用的时候，可能poo.size 都满足，实际上已经超过max.

**Comment by williamWANG0325** [comment]
我觉得上面第一个问题并不存在，注意这里
```
_task_cv.wait(lock, [this]{
	return !_run || !_tasks.empty();
}); // wait 直到有 task
```
- 条件变量的等待是有条件的。`_task_cv.wait`的条件就包括了任务队列不为空。
- 像你说的那种情况，如果多个commit同时发生，只唤醒了一个进程，那么该进程会一直执行到`_tasks`任务队列的所有任务全部执行完才会陷入wait阻塞。
- 另外，你所说的这种情况叫做条件变量的唤醒丢失（可以查查资料），而`wait`函数里的断言就是为了防止这情况发生。

但是第二个问题我觉得确实存在，毕竟stl::vector不是线程安全的。
就我感觉的话，这个线程池最好不要开`THREADPOOL_AUTO_GROW`，因为
1. 他对线程不安全的`_pool`并没有加锁（致命问题）
2. 这个`THREADPOOL_AUTO_GROW`只能自动增长，而不能自动减少，甚至连减少线程数量的函数接口都没有，也就是说这个线程数量没法管理，那这样的话还不如一开始直接定好线程数量。（这条纯属个人想法，比如说突然同时来了12个并发commit,导致开了12个线程，结果后面都并发量大大降低，这时开这么多线程感觉多少有点浪费）

**Comment by lzpong** [comment]
谢谢, 是有必要加锁和自动减少空闲线程 [commit 2e0c5e8](https://github.com/lzpong/threadpool/commit/2e0c5e8586947c4f7d354a81c058f9896f1a7f71)
