### ISSUE TITLE
thread pool 与 numactl 同时使用，出现捕获不到commit的tasks 

### ISSUE THREAD

**Issue by a32543254** [lzpong/threadpool#20]
thread pool 与 numactl 同时使用，出现捕获不到commit的tasks
例如 OMP_NUM_THREADS=27 numactl --localalloc --physcpubind=0-26     捕获不到
只有 当OMP_NUM_THREADS 大于 physcpubind的时候 才可以捕获到 
例如OMP_NUM_THREADS=27 numactl --localalloc --physcpubind=0-25

**Comment by lzpong** [comment]
numactl？ 没用过不太懂。
