### ISSUE TITLE
自动增长锁，必须有AUTO_GROW宏才会定义，但是在ifndef的判断后使用了它

### ISSUE THREAD

**Issue by JiadiLee** [lzpong/threadpool#21]
第98行，在#ifndef AUTO_GROW 的时候使用了只有ifdef 时才会定义的_lockGrow锁，在不进行自增的时候会导致编译不通过吧，在进行自增的时候，这个锁就没意义了？

**Comment by jsjrj01** [comment]
#ifndef THREADPOOL_AUTO_GROW 改为#ifnef THREADPOOL_AUTO_GROW

**Comment by JuncFang-git** [comment]
> #ifndef THREADPOOL_AUTO_GROW 改为#ifnef THREADPOOL_AUTO_GROW
应该是改为#ifdef THREADPOOL_AUTO_GROW 吧，你字母打错了。 @lzpong 所以作者不修改一下吗？我这边确实没有编译过，改完后才编译成功了
