### ISSUE TITLE
C++  multi-thread  call  python

### ISSUE THREAD

**Issue by jiangkunkun1993** [lzpong/threadpool#4]
hi，do you know how to use C++ multi-thread call python，can you help me ，thanks a lot，you can leave your email or wechat account ，my is 18811396527

**Comment by lzpong** [comment]
这里好多的哟 ↓↓↓
https://www.baidu.com/s?wd=%E4%BD%BF%E7%94%A8C%E5%A4%9A%E7%BA%BF%E7%A8%8B%E8%B0%83%E7%94%A8python
