### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by ruanhuanli** [lzpong/threadpool#7]
error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
“threadpool”: 不是“std”的成员

**Comment by vividwsw** [comment]
solved?

**Comment by muhaozhang** [comment]
-std=c++11

**Comment by Mr-shun** [comment]
linux下 
g++ Main.cpp -std=c++11 -pthread
亲试编译通过

**Comment by chenxingping** [comment]
> linux下 g++ Main.cpp -std=c++11 -pthread 亲试编译通过

你是在windows下的linux环境吧？
