### ISSUE TITLE
普通成员函数的调用参数问题

### ISSUE THREAD

**Issue by windflowerly** [lzpong/threadpool#8]
你好。
bind： .commit(std::bind(&Dog::sayHello, &dog))
这个好像不能带参数。

**Comment by qhq16** [comment]
参数带在bind里啊，为什么不能带参数

**Comment by windflowerly** [comment]
晓得了。参数类型问题。

**Comment by ZhuZouRong** [comment]
怎么解决的，我也碰到这个问题了

**Comment by ZhuZouRong** [comment]
这个是只能调用threadpool自己的成员函数吗

**Comment by qhq16** [comment]
用bind绑定类成员函数就可以使用commit了

**Comment by ZhuZouRong** [comment]
namespace dao
{
class Impl : public IStore
{
public:
    virtual int del(const std::string& strId);
};

std::threadpool executor;
std::future<int> test = executor.commit(std::bind(&dao::Impl::del, "id"));

是这样调用吗
编译报错 required from here
/usr/include/c++/5/functional:1426:7: error: static assertion failed: Wrong number of arguments for pointer-to-member
       static_assert(_Varargs::value

**Comment by qhq16** [comment]
bind绑定非静态成员函数需要类对象指针，而且你绑定的是虚函数，你可以看看bind的用法

**Comment by qhq16** [comment]
bind绑定非静态成员函数需要类对象指针，而且你绑定的是虚函数，你可以看看bind的用法
